[package]
name = "mqtt"
version = "0.1.0"
edition = "2024"
authors = ["heydabop <heydabop@gmail.com>"]
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
